### ISSUE TITLE
Unmatched left parenthesis in 2 Samuel 20:2

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#1]
The verse reads:

> \v 2 Mambo ndokudana VaGibhiyoni, ndokuti kwavari: (Zvino VaGibhiyoni vaiva vasiri vevana vaIsraeri, asi vevasiiwa veVaAmori, uye vana vaIsraeri vaiva vapika kwavari; asi Sauro wakatsvaka kuvauraya neshungu dzake pavana vaIsraeri naJudha\x + Josh. 9.3-17.\x*.

The opening **(** is not matched by any **)** in this or successive verses,

**Comment by teusbenschop** [comment]
Thanks for spotting this, it has now been fixed and will be in the repository within 10 minutes. Additionally I wondered why this has escaped our attention, and found that the Bibledit check on matching punctuation pairs was disabled. It has been enabled right away.

**Comment by DavidHaslam** [comment]
Reference is actually 21:2 not 20:2.

**Comment by DavidHaslam** [comment]
My typo in the issue title.
