### ISSUE TITLE
xrefs with a space before a full-stop

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#10]
There are 5 xrefs with a space before a full-stop.
```
001	\x + 10.26. 11.18. 1 Madz. 16 . 32.\x*
001	\x + 15.11. Isa. 2.21. 57.5 .\x*
001	\x + 2 Sam. 20.26 .\x*
002	\x + Eki. 27.3. 1 Madz. 7.45 .\x*
```
NB. The first column is the count.

**Comment by teusbenschop** [comment]
Thanks for finding these. I'll fix them at the very end when we're through with entering the xrefs.

**Comment by DavidHaslam** [comment]
xrefs are to be removed.
