### ISSUE TITLE
xrefs with multiple comma separated verses that could be simplified

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#12]
There are several such instances. 
Here is one example:
`\x + 1 Makor. 2.4,5,6,7,8,9,10,11,12,13,14,15: Mat. 1.3,4,5,6.\x*`
This could be simplified as:
`\x + 1 Makor. 2.4-15; Mat. 1.3-6.\x*`

Here's another:
`\x + 1 Makor. 23,24,25,26.\x*`
which reduces to:
`\x + 1 Makor. 23-26.\x*`

NB. My analysis is not exhaustive.

**Comment by teusbenschop** [comment]
Thanks for that. It's just that the original Cambridge Bible had them like this, but I agree, using the hyphen would be much clearer.

**Comment by DavidHaslam** [comment]
xrefs are to be removed.
