### ISSUE TITLE
Two xrefs containing an unexpected colon

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#13]
These are the two I found:
```
\x + 1 Makor. 2.4,5,6,7,8,9,10,11,12,13,14,15: Mat. 1.3,4,5,6.\x*
\x + 16:18,21; 12.4.\x*
```
The first in in **Ruth 4:18** and the second in **Exodus 16:16**.

Both colons should be a full-stop.
```
\x + 1 Makor. 2.4,5,6,7,8,9,10,11,12,13,14,15. Mat. 1.3,4,5,6.\x*
\x + 16.18,21; 12.4.\x*
```

The first example can also be simplified using verse ranges, as noted in the previous issue. e.g.
```
\x + 1 Makor. 2.4-15. Mat. 1.3,4,5,6.\x*
```

**Comment by DavidHaslam** [comment]
Fixed in the **Editing** branch of my fork.

**Comment by teusbenschop** [comment]
Thanks.
