### ISSUE TITLE
Table of Contents markers

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#2]
Your attention is drawn to the following observations:
1. None of the 66 books have **\toc1** marker (now required by ParaTExt)
2. Only 38 books have **\toc2** marker (also required by ParaTExt)
3. None of the 66 books have **\toc3** marker (optional in ParaTExt)

Even though this work is being maintainted with Bibledit, it still makes good sense for it to match the requirements of ParaTExt. 

Defining book abbreviations with **\toc3** would help to make sense of cross-references.

**Comment by teusbenschop** [comment]
I see. Well, something can be improved then. I would have a question about the \toc1 marker, and the \toc2 marker: What are they supposed to define, and what's the USFM docs for that? I understand that the \toc3 markers define the book abbreviations used in the xrefs?

**Comment by DavidHaslam** [comment]
1. **\toc1** is the verbose book name
2. **\toc2** is the short book name
3. **\toc3** is the abbreviation

USFM 2.4 documentation is [here](http://paratext.org/usfm)

USFM 3.0 is maintained [here](https://github.com/ubsicap/usfm)

From the former (example)...

> Implementing toc1 and toc2:
> The \toc1, \toc2, and \toc3 markers are provided to assist publishing tools in automating the generation of a table of contents. They can be included in the main text file for each scripture book, after \h. They are not for use directly within the front matter (FRT) peripheral file.
> 
> If you are working with the Publishing Assistant InDesign publishing path, the following markup is needed for generating an automatic table of contents:
> · Addition of \toc1 (and optionally \toc2) markers after \h, within each scripture book (\toc3 is not yet supported). 
> · Addition of the "\periph Table of Contents" (USFM 2.0 = \toc) sub-group marker within the FRT peripheral file. 
> Complete details of this process are provided in the linkWeb Publishing Assistant User Guide.

**Comment by DavidHaslam** [comment]
From the viewpoint of making a SWORD module, the helpful one would be **\toc3**
This will help in processing the localised cross-references in the OSIS XML.
Better to specify the abbreviations where they can be easily found than having to reverse engineer them from the extracted cross-references.

**Comment by teusbenschop** [comment]
Thanks for the refresher.

Thinking further, a possible good mechanical check for bibledit would be to check on the presense of the /toc[1-3] markers...

**Comment by DavidHaslam** [comment]
Seems good to me as an improvement.

**Comment by DavidHaslam** [comment]
FYI. The attached Zip file contains a snapshot of the USFM tag statistics.

[merged.usfm.tags.count.usfm.zip](https://github.com/teusbenschop/shona/files/1248507/merged.usfm.tags.count.usfm.zip)

**Comment by teusbenschop** [comment]
Thx man!

**Comment by DavidHaslam** [comment]
Method used:
1. TextPipe filter to concatenate all the **data** files from the downloaded repo.
2. TextPipe filter to extract and count all the USFM tags and append [tag descriptions](https://github.com/DavidHaslam/USFM-descriptions)
The latter is used so often that I added it to the Windows shell extensions on my PC.

_I started to use [TextPipe](http://www.datamystic.com/textpipe.html) in 2001_.

**Comment by teusbenschop** [comment]
\toc1 and \toc2 have been fixed today. Hopefully the \toc3 can be done on Monday, God willing.

**Comment by teusbenschop** [comment]
This has been fixed now and should be in the repository within 10 minutes from now.
