### ISSUE TITLE
Suggest insert Hebrew acrostic headings in Psalm 119 using the marker \qa

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#20]
**Psalm 119** currently has nothing to indicate to the reader that it is an **acrostic poem**.

Refer to https://github.com/teusbenschop/ndebele/issues/40
(where the wrong marker had been used)

**Comment by teusbenschop** [comment]
Yup, good idea!

**Comment by DavidHaslam** [comment]
I can readily copy the 22 lines from Psalm 119 in the the **ndebele** repo.

**Comment by teusbenschop** [comment]
Yes, that would be good!

**Comment by DavidHaslam** [comment]
```
\qa ALEPH א
\qa BETH ב
\qa GIMEL ג
\qa DALETH ד
\qa HE ה
\qa VAU ו
\qa ZAIN ז
\qa CHETH ח
\qa TETH ט
\qa JOD י
\qa CAPH כ
\qa LAMED ל
\qa MEM מ
\qa NUN נ
\qa SAMECH ס
\qa AIN ע
\qa PE פ
\qa TZADDI צ
\qa KOPH ק
\qa RESH ר
\qa SCHIN ש
\qa TAU ת

```

**Comment by DavidHaslam** [comment]
Committed to the **Editing** branch of my fork.
