### ISSUE TITLE
Canonical title is missing for 12 Psalms

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#22]
There should be **116** Psalms with a canonical title. Currently, only **104** Psalms have such a title.

We need to identify which are the **12** Psalms where the title is missing.

**Comment by DavidHaslam** [comment]
It's conceivable that the titles may already exist, but have been _wrongly_ tagged using **\s**

**Comment by teusbenschop** [comment]
Very likely that is the case.

**Comment by DavidHaslam** [comment]
No - it was a bug in my earlier analysis that failed to account that 12 titles began with added words.

The pattern `\p \add` needs to be changed to `\d \add`.

My TextPipe filter did not fix these exceptions.

**Comment by DavidHaslam** [comment]
Just fixed in the **Editing** branch of my fork. Pull request made.
