### ISSUE TITLE
Blank line in shared_dictionary

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#3]
Line 611 is blank.

Aside: 
1. What's the purpose of the shared_dictionary?
2. Is there a reason the words are not in sorted order?
3. Is the file up to date?

**Comment by teusbenschop** [comment]
It can be removed. It was for the old Bibledit-Gtk. The new plain Bibledit does not use it.

**Comment by teusbenschop** [comment]
Fixed.
