### ISSUE TITLE
Insert an \xt marker in each xref

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#4]
None of the 15739 xrefs in the shona data make use of the **\xt** marker.
It would be useful to insert one in each xref.

This would improve the conversion to OSIS XML en route to making a SWORD module.
i.e. It forces the creation of one **reference** element within the cross-reference note.
Though multiple references still have to be split in each note, at least this provides a better starting point.

**Comment by teusbenschop** [comment]
Is having the ```\xt``` marker required by the USFM (3.0) standard?

**Comment by DavidHaslam** [comment]
It's been part of USFM for ages. 

AFAIK, not compulsory in 3.0

**Comment by teusbenschop** [comment]
Okay, thanks. Our preference is to not have those \xt markers as they are superfluous. The mere fact that the \x... are xrefs indicates that there's target references. So the \xt is not needed, and just clutters up the USFM, as we think.

**Comment by teusbenschop** [comment]
As for conversion to OSIS, it is recommended that the tool to converts from USFM to OSIS handles omissions of non-enforced markup, e.g. in this case, the tool would handle the absence of \xt markup.

**Comment by DavidHaslam** [comment]
Agreed.
