### ISSUE TITLE
One xref in Exodus 3:14 has a book abbreviation with a missing full-stop

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#5]
**Exodus 3:14** reads:

`\v 14 Mwari ndokuti kuna Mozisi: NDIRI IYE WANDIRI IYE. Ndokuti: Ndizvo zvauchataura kuvana vaIsraeri: NDIRI IYE\x + 6.3. Joh. 8.58. VaHeb. 13.8. Zvak 1.4; 4.8.\x* wandituma kwamuri.`

The full-stop is missing from the last abbreviation. It should be `Zvak. 1.4; 4.8.`

**Comment by teusbenschop** [comment]
Thank you for spotting it. Fixed.

**Comment by teusbenschop** [comment]
It is "Revhitiko" in full. The Shona language has the special
characteristic that it does not have the letter L so it changes them all to
the letter R. :)
