### ISSUE TITLE
1320 xref abbreviations have two full-stops

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#6]
The following Shona book abberviations found in xrefs end with two full-stops.
```
683	Gen..
636	Num..
001	Rev..
```

**Comment by teusbenschop** [comment]
These are to be fixed at the end when we've done all of them. Because due to inconsistencies in the Ndebele Bible, where the xrefs get transferred from to Shona, there's going to be more duplicate full stops in Shona while xref entry continues.

**Comment by DavidHaslam** [comment]
I can readily do this fix with a simple bespoke TextPipe filter when the occasion arises.

**Comment by DavidHaslam** [comment]
xrefs are to be removed.
