### ISSUE TITLE
xrefs with full-stop as the delimiter between references

### ISSUE THREAD

**Issue by DavidHaslam** [teusbenschop/shona#9]
It looks like the semicolon is in the minority as the delimiter between references, even though this is generally preferred.

All in all, there are _only_ 2069 semicolons in the attached counted list of extracted xrefs!
[merged.xrefs.txt](https://github.com/teusbenschop/shona/files/1272451/merged.xrefs.txt)
cf. The total number of xrefs is 15739, of which 11601 are unique.

Here's an example of almost good practice: (found in **Exodus 1:11**)
`\x + 1 Madz. 9.19. 2 Makor. 8.4; 16.4; 17.12; 32.28.\x*`
With one minor improvement it would become:
`\x + 1 Madz. 9.19; 2 Makor. 8.4; 16.4; 17.12; 32.28.\x*`

However, **many** xrefs have a full-stop as the delimiter between references, which is both confusing and difficult to parse.

Here's just one example: (found in **2 Samuel 8:18**)
`\x + 1 Madz. 1.8. 2.25,29,34,35,46. 4.4. 1 Makor. 11.22,24. 27.5,34.\x*`
This would be preferable:
`\x + 1 Madz. 1.8; 2.25,29,34,35,46; 4.4. 1 Makor. 11.22,24; 27.5,34.\x*`

The comma is generally used as the delimiter between separate verses within the same chapter reference.
This is common practice, and the shona xrefs seem to follow this.

**Comment by teusbenschop** [comment]
Thanks for finding them. This is going to be a huge operations. Will look at the end of the project, whether there's still time left to implement this.

**Comment by DavidHaslam** [comment]
xrefs are to be removed.
